# Generated by Django 3.0.1 on 2020-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.CharField(default='avatar', max_length=30),
        ),
    ]
