# Generated by Django 3.0.1 on 2020-02-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200214_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
