# Generated by Django 3.0.1 on 2020-02-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
