# Generated by Django 3.0.1 on 2020-03-05 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200305_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmember',
            name='conversation2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Conversation'),
        ),
        migrations.AddField(
            model_name='messages',
            name='conversation1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Conversation'),
        ),
    ]
