# Generated by Django 3.0.1 on 2020-03-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20200305_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmember',
            old_name='conversation2',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='conversation1',
            new_name='conversation',
        ),
    ]
